# FROM golang:1.24-alpine AS builder

# WORKDIR /app
# COPY go.mod go.sum ./
# RUN go mod download
# COPY . ./
# ENV GOCACHE=/root/.cache/go-build
# RUN --mount=type=cache,target="/root/.cache/go-build" CGO_ENABLED=0 GOOS=linux go build -o /api-server cmd/server/main.go

# FROM alpine:latest
# RUN apk --no-cache add ca-certificates
# COPY --from=builder /api-server /
# EXPOSE 8181
# CMD ["/api-server"]


FROM golang:alpine

WORKDIR /app

# Install dependencies for go-fitz.
RUN apk update && apk add --no-cache git gcc musl-dev

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -tags musl -o api-server cmd/server/main.go

CMD ["./api-server"]

