-- User Table
CREATE TABLE IF NOT EXISTS "USER" (
  USER_ID UUID PRIMARY KEY,
  NAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  PASSWORD TEXT NOT NULL,
  ROLE TEXT NOT NULL
);

-- Interview Table
CREATE TABLE IF NOT EXISTS INTERVIEW (
  INTERVIEW_ID UUID PRIMARY KEY,
  USER_ID UUID NOT NULL,
  USERNAME TEXT NOT NULL,
  CREATED_AT TIMESTAMP,
  STATUS TEXT NOT NULL,
  RESUME_PATH TEXT NOT NULL,
  RESUME_SUMMARY JSONB,
  QUESTIONS JSONB,
  TRANSCRIPT JSONB,
  EVALUATION JSONB,
  CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES "USER" (USER_ID)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_interview_user_id ON INTERVIEW (USER_ID);
CREATE INDEX IF NOT EXISTS idx_interview_status ON INTERVIEW (Status);


---- Seed Data ----
INSERT INTO "USER" (USER_ID, NAME, EMAIL, PASSWORD, ROLE) VALUES
('4feb4f6b-0711-407c-98a5-f8a9a0c42d88', 'User1', 'user1@chayanai.com', 'admin', 'ADMIN'),
('4feb4f6b-0711-407c-98a5-f8a9a0c42d08', 'User2', 'user2@gmail.com', 'user', 'USER');